### ISSUE TITLE
Furious is not be able to run on this operating system.

### ISSUE THREAD

**Issue by AFrantsevich** [LorenEteval/Furious#44]
Hello!

```
Operating system information:
sysname: Linux
nodename: archlinux
release: 6.6.1-arch1-1
version: #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000
machine: x86_64
```

```
qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter

```

Can't I use it on arch?(

**Comment by LorenEteval** [comment]
```
Operating system information:
sysname: Linux
nodename: archlinux
release: 6.6.1-arch1-1
version: #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000
machine: x86_64
```

This message indicates that Qt is indeed working on your platform, but Furious detects that SystemTrayIcon is not supported (which should be since it's part of Qt library).

I'm not familar with archlinux. Seems like you should install `gnome-shell-extension-appindicator` so that it can display icons for you.

> qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter

This can be safely ignored.
