### ISSUE TITLE
X-Ray Core: failed to start core

### ISSUE THREAD

**Issue by khashayarxy** [LorenEteval/Furious#47]
Hey there,

Some of my clients have had problem with Furious connection and get "X-Ray Core: Failed to start core" error.

Do you guys know where is this coming from and what's the reason?

**Comment by khashayarxy** [comment]
Here's some images

![IMG_20231118_023028_078](https://github.com/LorenEteval/Furious/assets/42047526/666118f7-c50c-49a0-a3b6-02c525e19f6f)
![IMG_20231118_022937_064](https://github.com/LorenEteval/Furious/assets/42047526/6054c7c3-49a0-4985-94c1-8fce3351b511)

**Comment by LorenEteval** [comment]
> Xray-core: Connection test failed

Furious has built-in connection test in earlier versions. If connection test failed Furious refuses to perform connected action and the core will be terminated. It has been abandoned in newer version.

> Xray-core: Failed to start core

Furious detected a premature core exit with an exitcode indicating that the core failed to start. This is most likely caused by a port conflict, e.g. another application is using localhost 10808, 10809 ports, thus causing Xray-core proxy server failed to start.

**Comment by khashayarxy** [comment]
Thanks for the info. What's the best way to solve this instead of deleting other VPNs?

**Comment by LorenEteval** [comment]
> Thanks for the info. What's the best way to solve this instead of deleting other VPNs?

As long as they don't cause port conflict, they are fine.
