### ISSUE TITLE
Not proxying whole macOS as VPN

### ISSUE THREAD

**Issue by amirsaam** [LorenEteval/Furious#9]
I like the options in Furious but this is a big issue because many apps in macOS won't follow proxy rules like Telegram and you need to have a VPN Configuration and connect that to make these kind of apps follow it.
Is it possible for Furious to make this change?

**Comment by LorenEteval** [comment]
Yes. It will come as an experimental feature on both Windows and macOS. Since any TUN-like feature requires root(or administrator on Windows) privilege to operate under the hood, it will have conflict with existing feature that Furious currently has, such as startup on boot(Furious is implemented as booting and running in user privilege, not root privilege). At that time it will become user's responsibility to launch Furious as root(e.g. `sudo Furious`).

In any case, there will be a document on TUN feature, and Furious will try to be as user friendly as possible.

**Comment by LorenEteval** [comment]
Closed as completed in version 0.2.5.
